version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "test"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/client"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "tempy"
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "packages/server"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: npm
    directory: "."
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
  - package-ecosystem: docker
    directory: "packages/server"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - squash and merge
