name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build ./packages/server --file Dockerfile --tag sandbox-debugger
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        docker run -d --name sandbox-debugger -p 9228:9228 sandbox-debugger
        export NO_SERVER=1
        npm t
        docker kill sandbox-debugger
    - name: Tag docker image for public registry
      run: |
        docker tag sandbox-debugger jameskyburz/sandbox-debugger
        docker tag sandbox-debugger jameskyburz/sandbox-debugger:$(git describe --tags)
    - name: Login to public docker registry
      run: >
        echo ${{ secrets.DOCKERHUB_PASSWORD }} |
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Publish docker images to public registry
      run: |
        docker push jameskyburz/sandbox-debugger:latest
        docker push jameskyburz/sandbox-debugger:$(git describe --tags)
    - name: Tag docker image for github registry
      run: |
        docker tag sandbox-debugger docker.pkg.github.com/jameskyburz/sandbox-debugger/sandbox-debugger
        docker tag sandbox-debugger docker.pkg.github.com/jameskyburz/sandbox-debugger/sandbox-debugger:$(git describe --tags)
    - name: Login to github registry
      run: >
        echo ${{ secrets.GITHUB_REGISTRY_TOKEN }} |
        docker login docker.pkg.github.com --username JamesKyburz --password-stdin
    - name: Publish docker images to github
      run: |
        docker push docker.pkg.github.com/jameskyburz/sandbox-debugger/sandbox-debugger:latest
        docker push docker.pkg.github.com/jameskyburz/sandbox-debugger/sandbox-debugger:$(git describe --tags)

